#!/bin/bash

red='\e[31m'
grn='\e[32m'
wht='\e[0m'

USER="$(whoami)"
DEST="/u/cs452/tftp/ARM/${USER}/A4"
PROJECT_SOURCE_DIR=./src
EXTRA_FLAGS=""

if [ ! -d "build" ]; then
  mkdir build
fi

if [ ! -d "build/kern" ]; then
  mkdir build/kern
fi

if [ ! -d "build/user" ]; then
  mkdir build/user
fi

if [ ! -d "build/serv" ]; then
  mkdir build/serv
fi

if [ ! -d "build/util" ]; then
  mkdir build/util
fi



if [ "$1" == "clean" ]; then
  make clean
else
  
  for var in "$@"
    do

    if [ "$var" == "-d" ]; then
      EXTRA_FLAGS=${EXTRA_FLAGS}" DEBUG=-DDEBUG"
    fi

    if [ "$var" == "-c" ]; then
      EXTRA_FLAGS=${EXTRA_FLAGS}" CACHE=-DCACHE"
    fi

    if [ "$var" == "-o" ]; then
      EXTRA_FLAGS=${EXTRA_FLAGS}" OPT=-DOPT OPT_LEVEL=-O2"
    fi

    if [[ "$var" =~ ^-[0-9]+$ ]]; then
      EXTRA_FLAGS=${EXTRA_FLAGS}" AST=-DAST_LEVEL=${var:1}"
    fi

  done

  make clean
  #cp context_switch.s.in context_switch.s
  
  make ${EXTRA_FLAGS} 
  if [ $? -ne 0 ]; then
    echo -e "${red}FAILED to build!!${wht}"
    exit -1;
  fi
  
  ELF="$(find -name *.elf)"
  
  rm ${DEST}/*elf
  cp elf/*.elf ${DEST}/
  if [ $? -ne 0 ]; then
    echo -e "${red}FAILED to copy elf file to ${DEST}${wht}"
  fi
  
  chmod 777 ${DEST}/*.elf
  
  echo -e "${grn}Finished building, file name: \e[3;33m ${ELF} ${wht}"

fi
