#!/bin/bash

red='\e[31m'
grn='\e[32m'
wht='\e[0m'

USER="$(whoami)"
DEST="/u/cs452/tftp/ARM/${USER}/"
PROJECT_SOURCE_DIR=./src
DEBUG=""

cd ${PROJECT_SOURCE_DIR}

if [ "$1" == "clean" ]; then
  make clean
else

  if [ "$1" == "-d" ]; then
    DEBUG="DEBUG=-DDEBUG"
  fi

  make clean
  cp context_switch.s.in context_switch.s
  
  make ${DEBUG}
  if [ $? -ne 0 ]; then
    echo -e "${red}FAILED to build!!${wht}"
    exit -1;
  fi
  
  ELF="$(find -name *.elf)"
  
  rm ${DEST}/*elf
  cp *.elf ${DEST}
  if [ $? -ne 0 ]; then
    echo -e "${red}FAILED to copy elf file to ${DEST}${wht}"
  fi
  
  chmod 777 ${DEST}/*.elf
  mv *.o ../obj/
  mv *.s ../asm/
  mv *.elf ../elf/
  
  echo -e "${grn}Finished building, file name: \e[3;33m ${ELF} ${wht}"

fi
